# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka:9092
  schemaRegistry:
    enabled: true
    urls: ["http://schema-registry:8081"]
  protobuf:
    enabled: true
    schemaRegistry:
      enabled: true # This tells the proto service to consider the schema registry when deserializing messages
      refreshInterval: 1m # How often the compiled proto schemas in the cache should be updated

connect:
  enabled: true
  clusters:
    - name: connect
      url: http://connect:8083
